config/routes.rb
Rails.application.routes.draw do
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'letters' => 'static_pages#letters'
  get 'array_sorting' => 'static_pages#arr_sort'
  get '/update' => 'static_pages#update'
  get '/fill' => 'static_pages#fill'
  get '/sort' => 'static_pages#sort'
  
  
  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  resources :users, only: [:edit, :update, :show]
  resources :uploads, only: [:create, :destroy, :index, :update]

end

app/models/upload.rb
class Upload < ActiveRecord::Base
    mount_uploader :content, UploadUploader
    validates :content,  presence: true
    validate  :content_size

    private

    # Validates the size of an uploaded picture.
    def content_size
      if content.size > 5.megabytes
        errors.add(:content, "should be less than 5MB")
      end
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                              format: { with: VALID_EMAIL_REGEX },
                              uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper


  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination' 
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      @uploads = Upload.where("private = 't'")
    else
      @uploads = Upload.where("private = 'f'")
    end
    if @uploads.first.nil?
      @uploads = nil
    end
  end

  def about
  end
  
  def letters
  end
  
  def arr_sort
  end
  
  def fill
    @colors = [ "#000000", "#696969", "#808080", "#a9a9a9", "#c0c0c0", 
                "#d3d3d3", "#dcdcdc", "#f5f5f5", "#ffffff" ]
    @colors.shuffle!
    respond_to do |format|
      format.js
    end
  end
  
  def sort
    respond_to do |format|
      format.js
    end
  end
  
  def update
    if logged_in? 
      @upload = Upload.where("private = 't'").order("RANDOM()").first
    else
      @upload = Upload.where("private = 'f'").order("RANDOM()").first
    end
    respond_to do |format|
      format.js
    end
  end
end
  

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :index]
  
  def create
    @upload = Upload.new(upload_params)
    if params[:upload][:private] == '1' 
      @upload.update_attribute(:private, true)
    end
    @upload.save ? flash[:success] = "Uploaded!" 
                 : flash[:danger] = "Upload failed!"
    redirect_to request.referrer || uploads_path
  end
  
  def destroy
    @upload = Upload.find_by(id: params[:id])
    @upload.destroy
    flash[:success] = "File deleted"
    redirect_to request.referrer || uploads_path
  end
  
  def index
    @upload = Upload.new
    @uploads = Upload.all
  end
  
  def update
    @upload = Upload.find_by(id: params[:id])
    if @upload.private
      @upload.update_attribute(:private, false)
    else
      @upload.update_attribute(:private, true)
    end
    @upload.save
    flash[:success] = "Attribute changed"
    redirect_to request.referrer || uploads_path
  end
  
  
  private

    def upload_params
      params.require(:upload).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user,   only: [:edit, :update, :show]

  def new
  end
  
  def show
    @user = User.find(params[:id])
    @upload = Upload.new
    @uploads = Upload.all
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    # Before filters

    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    if logged_in?
      base_title = "Our own application <3"
    else
      base_title = "Project C.A.T"
    end
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
        <% if logged_in? %>
          <%= link_to "Our app", root_path, id: "logo" %>
        <% else %>
          <%= link_to "Project C. A. T.", root_path, id: "logo" %>
        <% end %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Animation stuff <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Letters", letters_path %></li>
                <li><%= link_to "Colored arrays", array_sorting_path %></li>
              </ul>
            </li>
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Upload content", uploads_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
          </ul>
        </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div class = "flash-messages">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_uploads.html.erb
<%= form_for(@upload, html: { multipart: true }) do |f| %>
  <div id="lgn-button">
    <%= f.submit "Upload", class: "btn btn-primary" %>
  </div>
  <div class="semilayer-text">
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.file_field :content, accept: 'image/jpeg,image/gif,image/png'%>
    <%= f.label :private, class: "checkbox inline" do %>
        <%= f.check_box :private %>
        <span>Make file private</span>
    <% end %>
  </div>
<% end %>

app/views/static_pages/_user_is_logged_in.html.erb
<div id="semilayer">
  <h1>Я люблю тебя, котёночек :З </h1>
  <div id = "semilayer-link">
    <%= link_to 'Ещё фоточек :)', '/update', remote: true %>
  </div>
</div>

app/views/static_pages/_user_is_not_logged_in.html.erb
<div id="semilayer">
  <h2>Hey, wanna see some kittens?</h2>
  <div id = "semilayer-link">
    <%= link_to 'I want MOAR kittens!', '/update', remote: true %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="semilayer-text">
    Hello there, friend! My name is Arthur and I use this site purely for testing 
    some Rails/js/styling stuff.
    Maybe in future there will be more interesting things as 
    I plan to test some new techniques there.
</div>
 

app/views/static_pages/arr_sort.html.erb
<% provide(:title, "Array sorting") %>
<div id = "array-background">
    <div class="btn-group">
    <%= button_to 'Press to get new array', '/fill', 
        :class => "btn btn-primary btn-block", :method => :get, remote: true %>
    <br/>
    <%= button_to 'And sort it!', '/sort', 
        :class => "btn btn-primary disabled btn-block", :method => :get, remote: true %>
    </div>
    <br/>
</div>

app/views/static_pages/fill.js.erb
$(function() {
  $('div.colors').remove();
  var state = <%=raw @colors%>;
  for (var i = 1; i < <%=@colors.length %>+1; i++) {
    $('div#array-background').append($('<div/>', {id: 'color-'+i, class: 'colors'}));
    $('#color-'+i).css("background-color", state[i-1]);
  };
  $('.disabled').removeClass('disabled');
});

app/views/static_pages/home.html.erb
<% if logged_in? %>
      <%= render 'static_pages/user_is_logged_in' %>
<% else %>
      <%= render 'static_pages/user_is_not_logged_in' %>
<% end %>

<% unless @uploads.nil? %>
      <div id="img-hover">
          <%=image_tag @uploads.sample.content.url %>
      </div>
<% end %>

app/views/static_pages/letters.html.erb
<% provide(:title, "Letters") %>
<div id = "letters-background">
  Hover over letters to see some magic
  <br/>
	<span>
    <div class="btn btn-primary">Or replace them with your text!</div>
    <br/>
    <input type="text" name="checkListItem" size="21"/>
  </span>
  <br/>
</div>

app/views/static_pages/sort.js.erb
var animate_swap = function(i, j, elem_1, elem_2, delay) {
  $('#color-'+(i+1))
    .queue(function (next) { 
      $(this)
        .slideUp(delay)
        .css("background-color", '#'+elem_1)
        .slideDown(delay);
      next(); 
    });
  $('#color-'+(j+1))
    .queue(function (next) { 
      $(this)
        .slideUp(delay)
        .css("background-color", '#'+elem_2)
        .slideDown(delay);
      next(); 
    });
};


function sortLoop(colors, j, i, delay) {
  setTimeout(function() {
    if (colors[j] > colors[j+1]) {
      var tmp = colors[j];
      colors[j] = colors[j+1];
      colors[j+1] = tmp;
      animate_swap(j, j+1, colors[j], tmp, delay);
    }
    j++;
    if (j < i) { 
      sortLoop(colors, j, i, delay);
    }
  }, ((colors[j] > colors[j+1]) ? (delay*2) : 0));
};

function firstSortLoop(colors, i, delay) {
  setTimeout(function() {
    sortLoop(colors, 0, i, delay);
    i--;
    if (i > 0) {
      firstSortLoop(colors, i, delay);
    }
    else $('.btn').removeClass('disabled');
  }, ((i < colors.length - 1) ? (delay*2*(i+1)) : 0));
};


$(function() {
  var colors = [];
  for (var i = 0; i < 9; i++) {
    colors[i] = $('#color-'+(i+1)).css("background-color").match(/\d+/g);
    colors[i] = Number(colors[i][0]).toString(16) + 
                Number(colors[i][1]).toString(16) + 
                Number(colors[i][2]).toString(16);
      
  };
  $('.btn').addClass('disabled');
  firstSortLoop(colors, colors.length - 1, 300);
});

app/views/static_pages/update.js.erb
$("#img-hover").html('<%=image_tag @upload.content.url %>');

app/views/uploads/_upload.html.erb
<ul class="list-unstyled" id="pictures">
    <li id="upload-<%= upload.id %>">
      <% if upload.private %>
        Private image |
        <%= link_to "make public", upload, method: :patch %>
      <% else %>
        Public image |
        <%= link_to "make private", upload, method: :patch %>
      <% end %>
      <%= image_tag(upload.content.url) %>
      <%= link_to "delete", upload, method: :delete,
                                       data: { confirm: "You sure?" } %>
    </li>
</ul>

app/views/uploads/index.html.erb
<% provide(:title, 'All uploads') %>

<div class="semilayer-text">
  <h2>All uploads</h2>
  <br></br>
</div>

  <%= render 'shared/uploads' %>
<div id = "lgn-button">
  <%= render @uploads %>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="semilayer-text">
  <h2>Update your profile</h2>
  <div class="row">
    <div id="lgn-button">
      <%= form_for(@user) do |f| %>
        <%= render 'fields', f: f %>
        <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="semilayer-text">
  Name : <%= @user.name %>
  <br></br> 
  Email : <%= @user.email %>
</div>